# SPDX-License-Identifier: GPL-2.0

# zuma dtbo
zuma_caimito_overlays := \
	zuma-ripcurrent24.dtbo \
	zuma-ripcurrent24-sapwood-komodo-caiman.dtbo \
	zuma-ripcurrent24-sapwood-tokay.dtbo \
	google-dts-ripcurrent/zuma-ripcurrent.dtbo \
	google-dts-ripcurrent/zuma-husky-proto1.dtbo \
	google-dts-ripcurrent/zuma-husky-proto1-wingboard.dtbo \
	google-dts-ripcurrent/zuma-husky-proto1_1.dtbo \
	google-dts-ripcurrent/zuma-husky-evt1.dtbo \
	google-dts-ripcurrent/zuma-husky-evt1_1.dtbo \
	google-dts-ripcurrent/zuma-husky-dvt1.dtbo \
	google-dts-ripcurrent/zuma-husky-pvt1.dtbo \
	google-dts-ripcurrent/zuma-husky-mp.dtbo \
	google-dts-ripcurrent/zuma-shiba-proto1.dtbo \
	google-dts-ripcurrent/zuma-shiba-proto1-wingboard.dtbo \
	google-dts-ripcurrent/zuma-shiba-proto1_1.dtbo \
	google-dts-ripcurrent/zuma-shiba-evt1.dtbo \
	google-dts-ripcurrent/zuma-shiba-evt1_b0.dtbo \
	google-dts-ripcurrent/zuma-shiba-evt1_1.dtbo \
	google-dts-ripcurrent/zuma-shiba-evt1_1-wingboard.dtbo \
	google-dts-ripcurrent/zuma-shiba-dvt1.dtbo \
	google-dts-ripcurrent/zuma-shiba-pvt1.dtbo \
	google-dts-ripcurrent/zuma-shiba-mp.dtbo \
	zuma-komodo-proto1-samsung-gnss.dtbo \
	zuma-komodo-proto1-broadcom-gnss.dtbo \
	zuma-komodo-proto1-broadcom-gnss-mag3.dtbo \
	zuma-komodo-proto1_1-samsung-gnss.dtbo \
	zuma-komodo-proto1_1-broadcom-gnss.dtbo \
	zuma-komodo-proto1_1-samsung-gnss-mag3.dtbo \
	zuma-caiman-proto1-samsung-gnss.dtbo \
	zuma-caiman-proto1-samsung-gnss-i2cm.dtbo \
	zuma-caiman-proto1-broadcom-gnss.dtbo \
	zuma-caiman-proto1-broadcom-gnss-mag3.dtbo \
	zuma-caiman-proto1-broadcom-gnss-i2cm.dtbo \
	zuma-caiman-proto1_1-samsung-gnss.dtbo \
	zuma-caiman-proto1_1-broadcom-gnss.dtbo \
	zuma-caiman-proto1_1-samsung-gnss-mag3.dtbo \
	zuma-tokay-proto1-samsung-gnss.dtbo \
	zuma-tokay-proto1-broadcom-gnss.dtbo \
	zuma-tokay-proto1_1-samsung-gnss.dtbo \
	zuma-tokay-proto1_1-broadcom-gnss.dtbo

# zuma dtb
zuma_caimito_dtbs := \
	google-dts-zuma/zuma-a0-foplp.dtb \
	google-dts-zuma/zuma-a0-ipop.dtb \
	google-dts-zuma/zuma-b0-foplp.dtb \
	google-dts-zuma/zuma-b0-ipop.dtb

# DPM overlays
zuma_caimito_overlays += \
	google-dts-zuma/zuma-dpm-eng.dtbo \
	google-dts-zuma/zuma-dpm-userdebug.dtbo \
	google-dts-zuma/zuma-dpm-user.dtbo

DTC_FLAGS_zuma-dpm-eng += -a 4096
DTC_FLAGS_zuma-dpm-user += -a 4096
DTC_FLAGS_zuma-dpm-userdebug += -a 4096

# zumapro dtbo
zumapro_caimito_overlays := \
	zumapro-ripcurrentpro.dtbo \
	zumapro-ripcurrentpro-sapwood-komodo-caiman.dtbo \
	zumapro-komodo-evt1-broadcom-gnss.dtbo \
	zumapro-komodo-evt1-samsung-gnss.dtbo \
	zumapro-komodo-evt1-broadcom-gnss-mag3.dtbo \
	zumapro-komodo-evt1-samsung-gnss-mag3.dtbo \
	zumapro-komodo-evt1-wingboard.dtbo \
	zumapro-komodo-evt1_1-broadcom-gnss.dtbo \
	zumapro-komodo-evt1_1-samsung-gnss.dtbo \
	zumapro-komodo-evt1_1-wingboard.dtbo \
	zumapro-komodo-dvt1.dtbo \
	zumapro-komodo-dvt1-wingboard.dtbo \
	zumapro-komodo-pvt1.dtbo \
	zumapro-komodo-mp.dtbo \
	zumapro-caiman-evt1-broadcom-gnss.dtbo \
	zumapro-caiman-evt1-samsung-gnss.dtbo \
	zumapro-caiman-evt1-broadcom-gnss-mag3.dtbo \
	zumapro-caiman-evt1-samsung-gnss-mag3.dtbo \
	zumapro-caiman-evt1-wingboard.dtbo \
	zumapro-caiman-evt1-broadcom-gnss-i2cm.dtbo \
	zumapro-caiman-evt1-samsung-gnss-i2cm.dtbo \
	zumapro-caiman-evt1_1-broadcom-gnss.dtbo \
	zumapro-caiman-evt1_1-samsung-gnss.dtbo \
	zumapro-caiman-evt1_1-wingboard.dtbo \
	zumapro-caiman-dvt1.dtbo \
	zumapro-caiman-dvt1-wingboard.dtbo \
	zumapro-caiman-dvt1-i2cm.dtbo \
	zumapro-caiman-pvt1.dtbo \
	zumapro-caiman-mp.dtbo \
	zumapro-tokay-evt1-broadcom-gnss.dtbo \
	zumapro-tokay-evt1-samsung-gnss.dtbo \
	zumapro-tokay-evt1-wingboard.dtbo \
	zumapro-tokay-evt1_1-broadcom-gnss.dtbo \
	zumapro-tokay-evt1_1-samsung-gnss.dtbo \
	zumapro-tokay-evt1_1-wingboard.dtbo \
	zumapro-tokay-dvt1.dtbo \
	zumapro-tokay-dvt1-wingboard.dtbo \
	zumapro-tokay-pvt1.dtbo \
	zumapro-tokay-mp.dtbo

# zumapro dtb
zumapro_caimito_dtbs := \
	google-dts-zumapro/zumapro-a0-foplp.dtb \
	google-dts-zumapro/zumapro-a0-ipop.dtb  \
	google-dts-zumapro/zumapro-a1-foplp.dtb \
	google-dts-zumapro/zumapro-a1-ipop.dtb

# DPM overlays
zumapro_caimito_overlays += \
        google-dts-zumapro/zumapro-dpm-eng.dtbo \
        google-dts-zumapro/zumapro-dpm-userdebug.dtbo \
        google-dts-zumapro/zumapro-dpm-user.dtbo

DTC_FLAGS_zumapro-dpm-eng += -a 4096
DTC_FLAGS_zumapro-dpm-user += -a 4096
DTC_FLAGS_zumapro-dpm-userdebug += -a 4096

# Usage:
#   $(call DTBS_overlay_template, overlay, base_dtb, suffix)
#
# This is a generic template to create the following construct:
#   <overlay>-<suffix>-dtbs := <base_dtb>.dtb <overlay>.dtbo
define DTBS_overlay_template
	$(1:%.dtbo=%-$(strip $3)-dtbs) := $2 $1
endef

# Usage:
#   $(call DTB_object_template, CONFIG_, overlay, suffix)
#
# This is a generic template to create the following construct:
#   dtb-$(CONFIG_) += <overlay>-<suffix>.dtb
define DTB_object_template
	dtb-$(strip $1) += $(2:%.dtbo=%-$(strip $3).dtb)
endef

# Usage:
#   $(call multi_dtbs_overlay, list_of_base_dtbs, list_of_overlays, CONFIG_)
#
# For each (base_dtb,overlay) pair, this will create the following constructs:
#   <overlay>-<base_dtb>-dtbs := <base_dtb>.dtb <overlay>.dtbo
#   dtb-$(CONFIG_) += <overlay>-<base_dtb>.dtb
define multi_dtbs_overlay
	$(foreach base, $1, \
		$(foreach overlay, $2, \
			$(eval $(call DTBS_overlay_template, $(overlay), $(base), $(notdir $(base:%.dtb=%)))) \
			$(eval $(call DTB_object_template, $3, $(overlay), $(notdir $(base:%.dtb=%))))))
endef

# Create the -dtbs and dtb-y constructs. We can do this by looping through the
# base dtbs and apply each overlay to it. Kbuild will use these -dtbs
# constructs to determine which dtbs are the base dtbs and which are the
# overlays. For the base dtbs, kbuild will expose the symbols as needed for the
# overlays. Additionally, kbuild will statically apply the overlay to the base
# dtb which could be used to verify the overlay applies cleanly.
$(call multi_dtbs_overlay, $(zuma_caimito_dtbs), $(zuma_caimito_overlays), y)
$(call multi_dtbs_overlay, $(zumapro_caimito_dtbs), $(zumapro_caimito_overlays), y)
